[Distribution]
Distribution=arch

[Content]
KernelModulesInitrd=no
Packages=
	base
	linux
	linux-firmware
	neovim
	sudo
	man
	man-db
	man-pages
	curl
	git
	wget
	openssh
	systemd
	python
	mkosi
	hyprland
	mkinitcpio
